import { useEffect, useState } from 'react';
import { useCarbon } from '../hooks/useCarbon';
import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/card';
import { Button } from '../components/ui/button';
import { LoadingSkeleton } from '../components/LoadingSkeleton';
import { ErrorState } from '../components/ErrorState';
import { WeatherInsight } from '../components/WeatherInsight';
import { Sparkles, ArrowRight, Wallet, Leaf, Zap } from 'lucide-react';
import { formatCO2, formatMoney } from '../utils/formatters';
import { Link } from 'react-router-dom';

export function AiCoach() {
  const { getAiRecommendations, loading, error } = useCarbon();
  const [data, setData] = useState<any>(null);

  const fetchRecommendations = async () => {
    try {
      const res = await getAiRecommendations();
      setData(res);
    } catch (err) {
      console.error(err);
    }
  };

  useEffect(() => {
    fetchRecommendations();
  }, []);

  if (loading) {
    return (
      <div className="space-y-6">
        <div className="flex items-center gap-3 text-emerald-500 mb-8 animate-pulse">
          <Sparkles className="w-8 h-8" />
          <h1 className="text-3xl font-bold">AI Coach is thinking...</h1>
        </div>
        <LoadingSkeleton variant="card" />
        <LoadingSkeleton variant="card" />
        <LoadingSkeleton variant="card" />
      </div>
    );
  }

  if (error && !data) {
    return <ErrorState message={error} onRetry={fetchRecommendations} />;
  }

  if (!data) return null;

  return (
    <div className="space-y-8 animate-in fade-in duration-500">
      <div className="flex flex-col md:flex-row md:items-end justify-between gap-6">
        <div>
          <div className="flex items-center gap-2 text-emerald-500 mb-2">
            <Sparkles className="w-6 h-6" />
            <h1 className="text-3xl font-bold text-white tracking-tight">AI Coach</h1>
          </div>
          <p className="text-slate-400 max-w-2xl">
            Personalized recommendations generated by Gemini AI, based on your recent carbon footprint, lifestyle, and local weather.
          </p>
        </div>
        <Link to="/eco-twin">
          <Button variant="outline" className="border-emerald-500/30 text-emerald-500 hover:bg-emerald-500/10">
            See Eco Twin <ArrowRight className="ml-2 w-4 h-4"/>
          </Button>
        </Link>
      </div>

      {data.weather_context && (
        <WeatherInsight weather={data.weather_context} />
      )}

      {/* Summary Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <Card className="bg-emerald-950/20 border-emerald-500/20">
          <CardContent className="p-6 flex items-center gap-4">
            <div className="p-3 bg-emerald-500/10 rounded-full">
              <Leaf className="w-6 h-6 text-emerald-500" />
            </div>
            <div>
              <p className="text-sm font-medium text-emerald-500/80 uppercase tracking-wider mb-1">Potential CO₂ Reduction</p>
              <p className="text-3xl font-bold text-emerald-400">{formatCO2(data.total_co2_savings)}</p>
            </div>
          </CardContent>
        </Card>
        
        <Card className="bg-amber-950/20 border-amber-500/20">
          <CardContent className="p-6 flex items-center gap-4">
            <div className="p-3 bg-amber-500/10 rounded-full">
              <Wallet className="w-6 h-6 text-amber-500" />
            </div>
            <div>
              <p className="text-sm font-medium text-amber-500/80 uppercase tracking-wider mb-1">Potential Monthly Savings</p>
              <p className="text-3xl font-bold text-amber-400">{formatMoney(data.total_cost_savings)}</p>
            </div>
          </CardContent>
        </Card>
      </div>

      <div className="space-y-4">
        <h2 className="text-xl font-semibold text-slate-200 flex items-center gap-2">
          <Zap className="w-5 h-5 text-amber-500"/> Action Plan
        </h2>
        <div className="grid grid-cols-1 gap-4">
          {data.recommendations.map((rec: unknown, idx: number) => (
            <Card key={idx} className="bg-slate-900/50 border-slate-800 hover:border-emerald-500/30 transition-colors">
              <CardContent className="p-6">
                <div className="flex flex-col md:flex-row justify-between gap-4">
                  <div className="flex-1">
                    <div className="flex items-center gap-3 mb-2">
                      <h3 className="text-lg font-semibold text-white">{rec.title}</h3>
                      <span className={`px-2 py-0.5 rounded text-xs font-medium ${
                        rec.difficulty === 'easy' ? 'bg-emerald-500/10 text-emerald-400' :
                        rec.difficulty === 'medium' ? 'bg-amber-500/10 text-amber-400' :
                        'bg-red-500/10 text-red-400'
                      }`}>
                        {rec.difficulty}
                      </span>
                    </div>
                    <p className="text-slate-400">{rec.description}</p>
                  </div>
                  
                  <div className="flex md:flex-col gap-4 md:gap-2 items-start md:items-end shrink-0 pt-2 border-t md:border-t-0 md:border-l border-slate-800 md:pl-6">
                    <div className="text-left md:text-right">
                      <span className="text-xs text-slate-500 uppercase font-medium block">Saves CO₂</span>
                      <span className="font-bold text-emerald-400">{formatCO2(rec.co2_savings_kg)}</span>
                    </div>
                    <div className="text-left md:text-right">
                      <span className="text-xs text-slate-500 uppercase font-medium block">Saves Money</span>
                      <span className="font-bold text-amber-400">{formatMoney(rec.cost_savings_inr)}</span>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>

    </div>
  );
}
